FROM python:3.10-slim

# Install dependencies
RUN apt-get update && apt-get install -y procps net-tools telnet default-mysql-client redis-tools vim git unzip jq bc iproute2 vnstat curl && rm -rf /var/lib/apt/lists/* && echo "alias ls='ls --color=auto'" >> $HOME/.bashrc

COPY requirements.txt .

RUN pip install --upgrade pip -v && pip install -r requirements.txt --no-cache-dir && pip install twscrape && pip install httpx[socks]
# pip install . --no-cache-dir
